; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
#INCLUDE p16f1786.inc

 __CONFIG _CONFIG1, _FOSC_ECH & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _CLKOUTEN_OFF & _IESO_ON & _FCMEN_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _WRT_OFF & _VCAPEN_OFF & _PLLEN_ON & _STVREN_ON & _BORV_LO & _LPBOR_OFF & _LVP_ON
;外设使用说明：RA0-7用于显示数码管数字，RC0-3用于选择数码管位
;RB0-3用于读入键盘输入的值
;用timer1做10ms延时


udata_shr    
DELAYTIME1    res 1h               ;???
DELAYTIME2    res 1h
KEY_VALUE     RES 1H
KEY_VALUE_LAST     RES 1H
ISPRESS	    RES 1H
ISPRESS_LAST	   RES 1H
KEY_FLAG     RES 1H


RES_VECT  CODE    0x0000            ; processor reset vector
GOTO    FIRST                   ; go to beginning of program
MAIN_PROG CODE                      ; let linker place main program

; TODO ADD INTERRUPTS HERE IF USED

 
CODE
INICIALISE;初始化代码
 BANKSEL OSCCON
 MOVLW B'01101000'
 MOVWF OSCCON ;设置震荡频率为4Mhz

 
 
 BANKSEL TRISA
 CLRF TRISA
 BANKSEL LATA
 CLRF LATA
 BANKSEL ANSELA
 ;CLRF ANSELA
 MOVLW B'00000000'
 MOVWF ANSELA;初始化端口a，端口a设置为输出方式

 BANKSEL TRISB
 CLRF TRISB
 BANKSEL LATB
 CLRF LATB
 BANKSEL ANSELB
 ;CLRF ANSELA
 MOVLW B'11111111'
 MOVWF ANSELB;初始化端口b，端口b设置为输入方式
;端口b的输入输出模式会在键盘扫描过程中更改
 
BANKSEL WPUB
MOVLW B'11111111'
MOVWF WPUB;设置rb弱上拉

BANKSEL OPTION_REG
MOVLW B'00000111'
MOVWF OPTION_REG;允许全局弱上拉，设置timer0分频256


 
BANKSEL TRISC
CLRF TRISC
BANKSEL LATC
CLRF LATC;


MOVLW .0
MOVWF KEY_VALUE_LAST
MOVWF KEY_VALUE
MOVWF KEY_FLAG
MOVWF ISPRESS
MOVWF ISPRESS_LAST
;初始化各标志变量
 
PAGESEL MAIN
GOTO MAIN;初始化完成后跳转执行主程序
 
;;;;;;;;;;;函数区;;;;;;;;;;;
KEYSCAN:

KEY1:;第一轮扫描，得到7，8，9，10四个按键是否被按下
    BANKSEL TRISB;
    MOVLW B'11111111'
    MOVWF TRISB;设置RB0-RB4均为输入模式检测外部电平
    BTFSC PORTB,0;若检测到RB0为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,0;若检测到RB0为低电平
    GOTO KEY7;则7键被按下
    BTFSC PORTB,1;若检测到RB1为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,1;若检测到RB1为低电平
    GOTO KEY8;则8键被按下
    BTFSC PORTB,2;若检测到RB2为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,2;若检测到RB2为低电平
    GOTO KEY9;则9键被按下
    BTFSC PORTB,3;若检测到RB3为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,3;若检测到RB3为低电平
    GOTO KEY10;则10键被按下
   
    KEY7:
	MOVLW .7
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN
    KEY8:
	MOVLW .8
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN
    KEY9:
	MOVLW .9
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN
    KEY10:
	MOVLW .10
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN
	
KEY2:;按键第二轮扫描，得到5，1，2三个按键的键值
    BANKSEL TRISB;
    MOVLW B'11111110'
    MOVWF TRISB;设置RB1-RB4均为输入模式检测外部电平，RB0为输出模式，输出低电平
    BANKSEL PORTB
    MOVLW B'00000000'
    MOVWF PORTB;输出的设置为低电平
    BTFSC PORTB,1;若检测到RB1为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,1;若检测到RB1为低电平
    GOTO KEY5;则5键被按下
    BTFSC PORTB,2;若检测到RB2为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,2;若检测到RB2为低电平
    GOTO KEY1;则1键被按下
    BTFSC PORTB,3;若检测到RB3为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,3;若检测到RB3为低电平
    GOTO KEY1;则1键被按下
    
    KEY5:
	MOVLW .5
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN
    KEY1:
	MOVLW .1
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN
    KEY2:
	MOVLW .2
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN

KEY3:;按键第三轮扫描，得到3，4按键的键值
    BANKSEL TRISB;
    MOVLW B'11111101'
    MOVWF TRISB;设置RB0，RB2,RB4均为输入模式检测外部电平，RB1为输出模式，输出低电平
    BANKSEL PORTB
    MOVLW B'00000000';输出引脚设置为低电平输出
    MOVWF PORTB;输出的设置为低电平
    BTFSC PORTB,2;若检测到RB2为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,2;若检测到RB2为低电平
    GOTO KEY3;则3键被按下
    BTFSC PORTB,3;若检测到RB2为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,3;若检测到RB2为低电平
    GOTO KEY4;则4键被按下
    
    KEY3:
	MOVLW .3
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN
    KEY4:
	MOVLW .4
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN

KEY4:;按键第四轮扫描，得到6按键的键值
    BANKSEL TRISB;
    MOVLW B'11111011'
    MOVWF TRISB;设置RB0，RB2,RB4均为输入模式检测外部电平，RB1为输出模式，输出低电平
    BANKSEL PORTB
    MOVLW B'00000000';输出引脚设置为低电平输出
    MOVWF PORTB;输出的设置为低电平
    BTFSC PORTB,3;若检测到RB2为低电平
    CALL DELAY;延时消抖
    BTFSC PORTB,3;若检测到RB2为低电平
    GOTO KEY6;则3键被按下
    
    KEY6:
	MOVLW .6
	MOVWF KEY_VALUE
	MOVLW .1
	MOVWF ISPRESS
	INCF KEY_FLAG
	RETURN
	
MOVLW .1;若KEY_FLA>1则有两个以上按键按下
SUBLW KEY_FLAG;减法
BTFSC STATUS,Z;判断其值是否为0
GOTO RE_KEY_VALUE;KEY_FLAG为1则返回按键值
MOVLW KEY_VALUE_LAST
MOVWF KEY_VALUE;若有多个键同时按下，则保留上一次扫描的键值
CLRF ISPRESS;
CLRF KEY_FLAG
GOTO LOOP;重新扫描
RE_KEY_VALUE:
CLRF KEY_FLAG
RETURN
   
    
    
DELAY:                         
MOVLW .10           
MOVWF DELAYTIME1        
DELAY_1
MOVLW .10     
MOVWF DELAYTIME2      
DELAY_2      
DECFSZ DELAYTIME2,1         
GOTO DELAY_2        
DECFSZ DELAYTIME1,1         
GOTO DELAY_1        
RETURN            ;延时函数，主要用于按键消抖

    
    
    
    
MAIN
MOVLW KEY_VALUE
MOVWF KEY_VALUE_LAST;保留上一次扫描中的键值
MOVLW ISPRESS
MOVWF ISPRESS_LAST

LOOP:
    CALL KEYSCAN
    MOVLW 0X1
    ANDWF ISPRESS;
    BTFSS STATUS,Z
GOTO LOOP 

GOTO MAIN
    
END  